package net.lunarjack.bossesandmore.entity.animation;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class ModAnimations {


	public static final Animation BATTLE_START = Animation.Builder.create(14.167666f)
			.addBoneAnimation("middle",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(5f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(7f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(8f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("middle",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 90f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 180f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(7f, AnimationHelper.createRotationalVector(0f, 270f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(8f, AnimationHelper.createRotationalVector(0f, 360f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(5f, AnimationHelper.createTranslationalVector(0f, 5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 6f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(7f, AnimationHelper.createTranslationalVector(0f, 7f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(8f, AnimationHelper.createTranslationalVector(0f, 8f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 90f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 180f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 270f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 360f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 450f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 540f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(7f, AnimationHelper.createRotationalVector(0f, 630f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(8f, AnimationHelper.createRotationalVector(0f, 720f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyelid",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 1f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 2f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3f, AnimationHelper.createTranslationalVector(0f, 3f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(5f, AnimationHelper.createTranslationalVector(0f, 5f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(6f, AnimationHelper.createTranslationalVector(0f, 6f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(7f, AnimationHelper.createTranslationalVector(0f, 8f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(8f, AnimationHelper.createTranslationalVector(0f, 8.27f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyelid",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 90f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 180f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 270f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 360f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 450f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 540f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(7f, AnimationHelper.createRotationalVector(0f, 630f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(8f, AnimationHelper.createRotationalVector(0f, 720f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyelid",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(9.958344f, AnimationHelper.createScalingVector(1f, 1f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(10f, AnimationHelper.createScalingVector(1f, 0f, 1f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(13.083434f, AnimationHelper.createScalingVector(1f, 0f, 1f),
									Transformation.Interpolations.LINEAR))).build();
	public static final Animation PRE_BATTLE = Animation.Builder.create(15f).looping().build();
	public static final Animation BATTLE_IDLE = Animation.Builder.create(2f).looping()
			.addBoneAnimation("middle",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("middle",
					new Transformation(Transformation.Targets.ROTATE,
							new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, -90f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, -180f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, -270f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createRotationalVector(0f, -360f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, -450f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, -540f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, -630f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createRotationalVector(0f, -720f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("head",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 8f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 9f, 0f),
									Transformation.Interpolations.LINEAR),
							new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 8f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyelid",
					new Transformation(Transformation.Targets.TRANSLATE,
							new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 8f, 0f),
									Transformation.Interpolations.LINEAR)))
			.addBoneAnimation("eyelid",
					new Transformation(Transformation.Targets.SCALE,
							new Keyframe(0f, AnimationHelper.createScalingVector(1f, 0f, 1f),
									Transformation.Interpolations.LINEAR))).build();
}